export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Picks } from './Picks';
export { default as Alert } from './Alert';
export { default as League } from './League';
export { default as Profile } from './Profile';
export { default as Admin } from './Admin';
export { default as Home } from './Home';
export { default as Pick6 } from './Pick6';
